# Create a pod and expose port 8080
apiVersion: v1
kind: Pod
metadata:
  name: kandula-pod
  labels:
    app: backend
spec:
   containers:
     - image: lihilure/kandula_image_app:first
       name: kandula
       ports:
         - containerPort: 5000
           name: http
           protocol: TCP
       env:
         - name: FLASK_ENV
           value: development
         - name: AWS_DEFAULT_REGION
           value: us-east-1
       envFrom:
         - secretRef:
              name: mysecret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - name: http
      port: 80 
      targetPort: 5000
      nodePort: 30036
      protocol: TCP