apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVVTTldZU1M0SE5BUVZCRVM=
  AWS_SECRET_ACCESS_KEY: ZElURE1aenRUZ0RXdHhtcFl1OVRkdk1sT2FIMjVQamh3dmQ3d2w5QQ==
  AWS_DEFAULT_REGION: dXMtZWFzdC0x