---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:purpose:
     - project
  instance-state-name: running
hostnames:
   - network-interface.association.public-ip
   - network-interface.addresses.private-ip-address
keyed_groups:
  - prefix: bastion
    key: tags['bastion']
  - prefix: consul
    key: tags['consul']
  - prefix: consul_agent
    key: tags['consul_agent']
#   - prefix: jenkins_server
#     key: tags['jenkins_server']
#   - prefix: jenkins_agent
#     key: tags['jenkins_agent']

